modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="strawberry"
version="1.0.0"
displayName="Strawberry Things"
authors="Your Name"
description='''
Strawberry Things
'''

[[dependencies.strawberry]]
modId="neoforge"
type="required"
versionRange="[20.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.strawberry]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[mixins]]
config="strawberry.mixins.json"